### ISSUE TITLE
HTML Report – ‘Newman html Report’ (htmlextra) – Gets stuck while opening the other tab i.e. 'Total Request' tab (due to Total data received: 38.28MB)[Feature Request]

### ISSUE THREAD

**Issue by poorna5500** [DannyDainton/newman-reporter-htmlextra#312] opened 2021-04-09 11:47 UTC
**HTML Report – ‘Newman html Report’ (htmlextra) – Gets stuck while opening the other tab i.e. 'Total Request' tab (due to Total data received: 38.28MB)**

**Description** - HTML Report – ‘Newman HTML Report’ (htmlextra) – Gets stuck while opening the other tab i.e. ‘Total Request’ tab and unable to view all the ‘Expanded Folders’ shows blank (due to Total data received: 38.28MB)

#How -
After the execution through command-line, opening the newman report – its opens but taking a long time and get stuck unable to view the all the ‘Expanded Folders’ shows blank.

Teams, Please help me how to fix this issue – maybe this due to large data i.e. Total data received: 38.28MB

**Expected Result**
The html report should open within 15-20 sec able to view all the ‘Expand Floder’ data without any issues.

**Attachment**
<img width="1851" alt="ReportIssue" src="https://user-images.githubusercontent.com/82158472/114175241-69bb0200-9957-11eb-8e6d-8ea7cfe74c45.png">

**Comment by DannyDainton** [comment] 2021-04-09 11:49
Duplicate of https://github.com/DannyDainton/newman-reporter-htmlextra/issues/259

**Closed by DannyDainton** 2021-04-09 11:49 UTC
Labels: enhancement
