### ISSUE TITLE
[BUG] --reporter-htmlextra-hideRequestBody "login 200" does not work with single quotes

### ISSUE THREAD

**Issue by frille70** [DannyDainton/newman-reporter-htmlextra#339] opened 2021-09-08 11:52 UTC
**What Are You Seeing**

When I run my neman command, with the htmlextra, in Jenkins and use the option --reporter-htmlextra-hideRequestBody "login 200" the double quotes gets converted to single quotes by Jenkins when the job executes. This makes the option not work. It does not hide the request body. All other options that I use, such as setting the title of the html report, are working just fine with the single quote conversion that Jenkins make, so it is only the hideRequestBody option of the ones I am using that is having this issue. I verified this by running the same newman command locally on my PC using both double and single quotes. It works only when I use double qoutes.

**Steps To Reproduce The Issue**

Run a newman command with htmlextra reporter and include the option --reporter-htmlextra-hideRequestBody with any request name and try with both single and double quotes around the name

**Screenshots and Gifs**
I'm a visual person so it would be a HUGE help if you shared a screenshot of what you're seeing....
_A picture paints a thousand words..._

**Collection and Environment Files**

Any files that would allow me to reproduce the issue locally...

**Version and Platform Information:**
 - `newman` version  5.3.0
 - `newman-reporter-htmlextra` version 1.22.1
 - OS Windows and Linux
 - The CLI command you've used to start Newman
 
 This command is in my execution shell in the Jenkins job:
 
 NODE_OPTIONS="--max-old-space-size=2048" newman run postman/pubapiSanity.postman_collection.json -e postman/environment/pubapi_variables.postman_environment.json -n 1 --color off --disable-unicode --delay-request 200 --timeout-request 30000 --timeout-script 90000 --env-var "userName=$USER" --env-var "password=$PASSWORD" --env-var "intApi=$INTAPIKEY" --env-var "extApi=$EXTAPIKEY" --env-var "currentEnv=$ENVIRONMENT" --env-var "jenkins=yes" -r htmlextra,cli --reporter-htmlextra-export ./report.html --reporter-htmlextra-showOnlyFails --reporter-htmlextra-title "PubApi Sanity Check, target $ENVIRONMENT" --reporter-htmlextra-hideRequestBody "login 200" --reporter-htmlextra-hideRequestBody "login 403 wrongPass" --reporter-htmlextra-hideRequestBody "login 403 wrongName"

**Additional Context**

This is command from the log from the Jenkins run:
+ newman run postman/pubapiSanity.postman_collection.json -e postman/environment/pubapi_variables.postman_environment.json -n 1 --verbose --color off --disable-unicode --delay-request 200 --timeout-request 30000 --timeout-script 90000 --env-var userName=**** --env-var password=**** --env-var 'intApi=****' --env-var 'extApi=****' --env-var currentEnv=dev --env-var jenkins=yes -r htmlextra,cli --reporter-htmlextra-export ./report.html --reporter-htmlextra-showOnlyFails --reporter-htmlextra-title 'PubApi Sanity Check, target dev' --reporter-htmlextra-hideRequestBody 'login 200' --reporter-htmlextra-hideRequestBody 'login 403 wrongPass' --reporter-htmlextra-hideRequestBody 'login 403 wrongName'

You see here that all the double quotes are now converted to single. But, again, it works fine for all options but the --reporter-htmlextra-hideRequestBody

Any contextual information that might relate to the problem?

Is there any workaround to make Jenkins leave the double quotes as is? I have tried several things from googling but with no luck. It always adds single quotes no matter what I am trying

**Comment by DannyDainton** [comment] 2021-09-08 16:35
I'm unable to reproduce this issue using either single or double quotes - both types are hiding the request body for me.

Can you confirm that it's also not working locally for you with single quotes? 

Have you also tried reordering the structure to not have these at the end of the command, not saying that will fix it but any variation of what you're doing is going to be a good thing.

**Comment by DannyDainton** [comment] 2021-09-14 09:30
@frille70 This isn't something I'm able to reproduce so I'm not able to actually do anything about it.

**Comment by frille70** [comment] 2021-09-14 09:32
Hi
I will get back to you in this matter. I will try your suggestions. Thank you

**Comment by DannyDainton** [comment] 2021-09-17 06:09
Closing this issue for now. We can look to reopen it if more information about the problem can be uncovered.

**Closed by DannyDainton** 2021-09-17 06:09 UTC
Labels: bug

**Comment by frille70** [comment] 2021-09-24 15:07
Hi
Still an issue. I just verified locally that the option to exclude req body of a certain request does not work with single  quotes:
newman run /psGit/pubtool/postman/pubapiSanity.postman_collection.json -e /psGit/pubtool/postman/environment/pubapi_variables.postman_environment.json -n 1  --color off --disable-unicode --delay-request 200 --timeout-request 30000 --timeout-script 90000 --env-var "userName=xxxxx" --env-var "password=xxxxxxx" --env-var "intApi=Bearer xxxxxxx-77b013b78711" --env-var "extApi=Bearer xxxxxx-62794b74" --env-var "currentEnv=dev" --env-var "jenkins=no" -r htmlextra,cli --reporter-htmlextra-showOnlyFails --reporter-htmlextra-export ./report.html --reporter-htmlextra-logs --reporter-htmlextra-title ‘PubTool Sanity Check’ --reporter-htmlextra-hideRequestBody ‘login 200’

This does not exclude the login 200 request body

Setting the title does, however, work just fine with both single and double quotes (--reporter-htmlextra-title ‘PubTool Sanity Check’) I noticed though that if you set the title with single quotes the single quotes will be included in the title in the report, but with double quotes it will just print the title without any quotes:
With single quotes:  --reporter-htmlextra-title ‘PubTool Sanity Check’ -> title: ‘PubTool Sanity Check’
With double quotes: --reporter-htmlextra-title “PubTool Sanity Check” -> title: PubTool Sanity Check

I also tried as you suggested to put the --reporter-htmlextra-hideRequestBody ‘login 200’ in different order among the other options but it did not make any difference.

Regards, and have nice weekend
/Fredrik
