### ISSUE TITLE
[BUG] Request Details in the Total Requests Tab not showing

### ISSUE THREAD

**Issue by CptDaimox** [DannyDainton/newman-reporter-htmlextra#336] opened 2021-08-31 14:36 UTC
**What Are You Seeing**

My reports won't show any request details in the total requests tab under the iterations. I am running the latest newman version (5.2.4) and the latest htmlextra version (1.22.0). I tried other Enviroments and Collections but nothing changed.

However downgrading to 1.21.0 worked and showed the normal behaviour.

**Steps To Reproduce The Issue**
1. Install latest newman-reporter-htmlextra
2. run newman with it 
**Screenshots and Gifs**
output on latest version (1.22.0)
![image](https://user-images.githubusercontent.com/46007489/131520478-8529b409-abc6-4224-8469-a56780cd6392.png)
output when downgrading to previous version (1.21.0)
![image](https://user-images.githubusercontent.com/46007489/131520737-ebc826ae-4d76-4ffc-8cbf-d12322efb566.png)

**Collection and Environment Files**

I tried this with different files and even newly created collections with no enviroments

**Version and Platform Information:**
 - OS: Windows 10, macOS Big Sur  11.5.2, Debian GNU/Linux 9.11
 - The CLI command: newman run collection.json -e enviroment.json -r htmlextra

**Comment by DannyDainton** [comment] 2021-09-01 11:14
Hmm, that doing seem right. I've not heard anyone else raise this issue for that version so it's a little strange.

Are you about to do a full uninstall `npm uninstall -g newman newman-reporter-htmlextra` followed by a full install `npm install -g newman newman-reporter-htmlextra` - I know it sounds like I'm just telling you something you've tried already but it's been know to help.

Are you able to share a watered down collection that shows the issue so that I can try and reproduce it on my side?

**Comment by CptDaimox** [comment] 2021-09-01 13:05
Yes I tried again now, but still the same result. I just tested it with a new Collection, that has no tests, just a request to google. The result is the same on the current version, but downgrading works.
here is the collection: [collection.json.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/7091249/collection.json.zip)

**Comment by DannyDainton** [comment] 2021-09-01 13:18
Interesting, I'll take a look at this later. I have my day job to do first :D

**Comment by notfazed274** [comment] 2021-09-02 06:23
Same issue here Danny, insanely tryin' to find what was my mistake, then I find theres another pal with the same problem. There you go an attachments.


![bug1newman](https://user-images.githubusercontent.com/89963622/131792714-6306a2d3-a563-4589-88ee-17a4feae0d8b.JPG)

**Comment by DannyDainton** [comment] 2021-09-02 08:17
Arh crap...ok, thanks for also flagging the issue.

In the short term it looks like the previous version is working as expected, I would advise downgrading until I sort of what's happening here. 😢

**Comment by np185092** [comment] 2021-09-02 19:43
May i know when this bug will resolve ?. Html extra 1.21.0 version worked fine. With htmlextra 1.22.0, we are not able to see requests and responses in the report. if the bug is not immediately resolved. can you tell steps to downgrade the version or provide any workaround 
![image](https://user-images.githubusercontent.com/67425343/131906273-88f73f25-d74a-4a98-bd0f-a44df24383de.png)

**Comment by DannyDainton** [comment] 2021-09-02 19:52
I don't really give a 'time to fix' for this project, it's not my full-time focus or my day job. 

I don't like seeing anything broken but I also don't have endless time to work on everything. 

It will be worked on as soon as I or anyone else who might provide a fix, becomes free.

You should be able to target a specific version with `npm i -g newman-reporter-htmlextra@1.21.0`

**Comment by DannyDainton** [comment] 2021-09-03 08:35
I've just pushed a new package version `1.22.1` to NPM, would anyone be able to confirm this has solved the issue please 🙏🏻

**Comment by notfazed274** [comment] 2021-09-03 20:37
thanks danny!

![htmlextrarep](https://user-images.githubusercontent.com/89963622/132062954-e4db5878-e425-4f56-9b27-25ee81d51d2e.JPG)

**Comment by DannyDainton** [comment] 2021-09-03 21:30
I did nothing but push out the new version - @praveendvd is the person to thank 🏆

**Comment by DannyDainton** [comment] 2021-09-03 21:31
Closing this one out now, we can always open it again 😁

**Closed by DannyDainton** 2021-09-03 21:31 UTC
Labels: bug
