### ISSUE TITLE
HTML report is not opening soon since file size is very less for eg: 1mb to 2 mb

### ISSUE THREAD

**Issue by ranjan1522** [DannyDainton/newman-reporter-htmlextra#346] opened 2021-11-26 06:20 UTC
![newman](https://user-images.githubusercontent.com/28652331/143535930-a7fb19cf-5c43-4207-bab9-099ee5cb091b.png)

**Comment by DannyDainton** [comment] 2021-11-26 07:05
Duplicate of #259

**Closed** 2021-11-26 07:05 UTC
Labels: bug, duplicate
