### ISSUE TITLE
Node js and HTML Reporter Installation issues

### ISSUE THREAD

**Issue by ThePoojaChavan** [DannyDainton/newman-reporter-htmlextra#412] opened 2023-08-22 15:14 UTC
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

HTML extra reporter issues with Nodejs installation

### Steps To Reproduce The Issue
```
Installations and Versions on my computer
C:\>newman -v
5.3.2

C:\>node -v
v18.17.1

Getting stuck with:
When I install HTML reporter package with the command

npm install -g newman-reporter-htmlextra, I get the error

C:\Users\AppData\Roaming\npm\node_modules\npm\lib\cli.js:48

    throw err

    ^

Error: Cannot find module 'C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\signal-exit\dist\cjs\index.js'

    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)

    at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)

    at resolveExports (node:internal/modules/cjs/loader:567:14)

    at Module._findPath (node:internal/modules/cjs/loader:636:31)

    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)

    at Module._load (node:internal/modules/cjs/loader:922:27)

    at Module.require (node:internal/modules/cjs/loader:1143:19)

    at require (node:internal/modules/cjs/helpers:121:18)

    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\gauge\lib\index.js:5:14)

    at Module._compile (node:internal/modules/cjs/loader:1256:14) {

  code: 'MODULE_NOT_FOUND',

  path: 'C:\\Users\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\signal-exit\\package.json'

}

```

### Full Newman Command Or Node Script

```bash
npm install -g newman-reporter-htmlextra
```

### HTMLEXTRA Version

1.22.11

### Newman Version

5.3.2

**Comment by DannyDainton** [comment] 2023-08-22 16:14
Hey @ThePoojaChavan 

Have you tried with an older version of node, you can switch between these suing something like `nvm`. I suspect that there is something in the reporter than is not currently compatible with version 18.

I would need to do a lot of testing to she what it might be so in the meantime, lowering the node version might unblock you.

**Comment by ThePoojaChavan** [comment] 2023-08-22 16:47
Hi Danny,
I just removed version 18 and installed an old version of node

C:\>node -v
v16.16.0

Same issue once again

**Comment by DannyDainton** [comment] 2023-08-22 17:00
The only thing I can really say is to do a full uninstall, followed by an install.

```
npm uninstall -g newman newman-reporter-htmlextra
```

then 

```
npm install -g newman newman-reporter-htmlextra
```

It's a tricky one to debug without being on your machine - There's roughly 170K downloads a week and this is the first time i've seen anyone mention an installation issue. I would have thought that would have been flagged by more people 🤔

**Comment by ThePoojaChavan** [comment] 2023-08-22 17:30
Did a full uninstall and re-installed Danny, same issue.

Don't know how to solve this, maybe I would just go with CLI for the time being.

Thanks

**Comment by DannyDainton** [comment] 2023-08-22 18:08
Are you able to install and use any of the other custom reporters for Newman?

**Comment by DannyDainton** [comment] 2023-08-22 18:40
That sounds like the issue is with your environment and the installation of node on your machine as it's not limited to only my reporter. 

I would try and completely remove node from your machine and delete any node modules that you may have installed. Before trying everything again. 

I'm going to close this issue as it isn't something specific to this reporter and I wouldn't be changing anything. Happy to talk more about this over on the Postman Community Forum.

**Closed** 2023-08-22 18:40 UTC
Labels: type: bug, state: triaged

**Comment by ThePoojaChavan** [comment] 2023-08-22 18:49
Already removed all folders/ modules related to node, npm. 

Re-installed nodejs v 16. Sadly, the issue is still there.

Thanks for your time and help Danny.

Regards

**Comment by w4dd325** [comment] 2023-08-23 16:02
To be honest, it looks like an issue with Node... maybe try completely uninstalling Node.JS  and then reinstall. 
Some info on uninstalling it [here](https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows).

You could also try uninstalling NPM first then reinstalling
npm uninstall -g npm
npm install -g npm

You could also check your global install path
npm config get prefix
If it is wrong then update it using:
npm config set prefix "C:\Users\<your-username>\AppData\Roaming\npm"

**Comment by ThePoojaChavan** [comment] 2023-08-23 16:55
Appreciate your reply, James.

I have uninstalled and completely removed all packages before re-installing lower node version.

npm uninstall -g npm gives same previous error message.

npm config get prefix also gives same error message.

Will it help if I attach cli.js, package.json and index.js?

**Comment by w4dd325** [comment] 2023-08-23 17:30
If 'npm config get prefix' doesn't work then I think this is very much an issue with your computer/environment. 
It sounds like your computer simply doesn't know where the NPM modules are stored. 

Have you tried setting as I mentioned above?
`npm config set prefix "C:\Users<your-username>\AppData\Roaming\npm"`

**Comment by ThePoojaChavan** [comment] 2023-08-23 17:45
Just tried the setting 
npm config set prefix "C:\Users\AppData\Roaming\npm"

Same error.

**Comment by w4dd325** [comment] 2023-08-23 17:49
If this is a corporate machine I suggest you speak to your system administrators. 
If it's a personal machine, I'm not sure what else to suggest, but I think it is definitely your environment settings, not the reporter.

**Comment by ThePoojaChavan** [comment] 2023-08-23 17:56
It's a personal machine.  

I have checked PATH- system variables; just thinking aloud if it could be related to Windows 11. Other than that, I do not really know what else settings are causing the issue.  

Thanks for all your help, appreciate it.
