### ISSUE TITLE
Getting error while  executing Newman command line

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#243] opened 2020-06-30 14:05 UTC
I amgetting error when I am executing Newman command. Could anyone please provide the solution for this. Here is my Newman command.

newman run Digital_API.postman_collection.json -r htmlextra --reporter-htmlextra-title "Digital API Automation report" -d TestData_SIT.json

Here is a error:

<--- Last few GCs --->

[28152:000002D62F1A7200] 4378103 ms: Mark-sweep 2036.9 (2055.4) -> 2032.8 (2055.1) MB, 1328.3 / 0.0 ms (average mu = 0.387, current mu = 0.484) allocation failure scavenge might not succeed
[28152:000002D62F1A7200] 4380001 ms: Mark-sweep 2036.6 (2055.1) -> 2032.8 (2054.9) MB, 1684.9 / 0.0 ms (average mu = 0.253, current mu = 0.113) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

0: ExitFrame [pc: 00007FF7202577DD]
1: StubFrame [pc: 00007FF7202C035E]
Security context: 0x01bff81408d1
2: /* anonymous */ [0000003AC8CB78D9] [evalmachine.:13784] [bytecode=0000031353F12CA1 offset=0](this=0x033a74703c29 ,0x01bff817c1d1 <String[#3]: key>)
3: arguments adaptor frame: 3->1
4: Ht [0000004D77A92F89] [evalmachine.:~13784] [pc=0000031C6ECBD37A](this=0x033a747...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 00007FF71F64470F napi_wrap+113583
2: 00007FF71F5EF7D6 v8::base::CPU::has_sse+66646
3: 00007FF71F5F05D6 v8::base::CPU::has_sse+70230
4: 00007FF71FE042EE v8::Isolate::ReportExternalAllocationLimitReached+94
5: 00007FF71FDEC3C1 v8::SharedArrayBuffer::Externalize+833
6: 00007FF71FCB890C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
7: 00007FF71FCC3B40 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
8: 00007FF71FCC0664 v8::internal::Heap::PageFlagsAreConsistent+3204
9: 00007FF71FCB5E63 v8::internal::Heap::CollectGarbage+1283
10: 00007FF71FCB44D4 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF71FCD56DD v8::internal::Factory::NewFillerObject+61
12: 00007FF71FA3BF61 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1665
13: 00007FF7202577DD v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 00007FF7202C035E v8::internal::SetupIsolateDelegate::SetupHeap+975566
15: 00007FF7201DC78C v8::internal::SetupIsolateDelegate::SetupHeap+42748
16: 00007FF7201D5ABC v8::internal::SetupIsolateDelegate::SetupHeap+14892
17: 0000031C6ECBD37A

**Comment by DannyDainton** [comment] 2020-06-30 14:18
Hey @svarshney2311 

Are you seeing the same thing without using the htmlextra reporter? If you remove the `-r htmlextra --reporter-htmlextra-title "Digital API Automation report"` part and run it, is the same thing happening?

As an issue report, that doesn't tell me or the other places that you have posted it, any information about what you're doing.

- How big is the collection? How many requests?
- What's in the data file?
- How many iterations is it running?
- What versions of Newman/Node/htmlextra are you using? 
- Are you just running this from the command line or in a CI pipeline?
- Have you tried uninstalling Node/Newman and trying everything again?

Telling people the command you're running and then dumping some unformatted error message into an Issue and expecting people to either know or begin to see what the problem is not a good way of going about this problem.

**Comment by svarshney2311** [comment] 2020-06-30 14:33
Sorry for the less information. here is the full information.

I have tried removing report section and I can see the execution happenning in command line.


- There are 90 requests in the collection, some of the requests is called multiple times.so total request to be executed will be around 150+(size of Json collection 450 KB)
-- each requests has TestData set up ( Size 12 KB)
-- 1 iteration is running
-- Newman 5.1.0, Node v12.18.0, 
--I am running from the command line
-- I have tried reinstalling node and Newman , but issue is still there.


Below is a result from command line execution:
────────────┬────────────────────┬────────────────────┐
│                         │           executed │             failed │
├─────────────────────────┼────────────────────┼────────────────────┤
│              iterations │                  1 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│                requests │                180 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│            test-scripts │                378 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│      prerequest-scripts │                347 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│              assertions │                124 │                  3 │
├─────────────────────────┴────────────────────┴────────────────────┤
│ total run duration: 1m 42.8s                                      │
├───────────────────────────────────────────────────────────────────┤
│ total data received: 175.77KB (approx)

**Comment by DannyDainton** [comment] 2020-06-30 14:57
I'm not sure what you would like me to do about this, to be honest.

Is this _only_ throwing that error when htmlextra is used? Have you tried with any other reporter?

**Comment by svarshney2311** [comment] 2020-06-30 15:01
Below also works fine 
newman run Digital_API.postman_collection.json -r htmlextra -d TestData_SIT.json

But when I am using  --reporter-htmlextra-title "Digital API Automation report" in command line , I am getting error after long time.

**Comment by DannyDainton** [comment] 2020-06-30 15:11
Do you need the title in there?

**Comment by svarshney2311** [comment] 2020-06-30 15:13
Yes I want to change the tiltle tov our Project name. Is there way to change internally in any folder??

**Comment by DannyDainton** [comment] 2020-06-30 15:15
What's the version of the reporter you're using?

**Comment by svarshney2311** [comment] 2020-06-30 15:34
newman-reporter-htmlextra@1.17.1

**Comment by DannyDainton** [comment] 2020-06-30 16:12
You could grab this template and save it locally - https://github.com/DannyDainton/newman-reporter-htmlextra/blob/master/lib/dashboard-template.hbs

You can hardcode the title you want here - https://github.com/DannyDainton/newman-reporter-htmlextra/blob/347d57a9097d04d5856a4250663f222149c837e7/lib/dashboard-template.hbs#L452

Then using the `--reporter-htmlextra-template template.hbs` flag from the command line, this will use it in the run.

**Comment by DannyDainton** [comment] 2020-06-30 16:31
The issue looks like it relates this one with Newman as per this issues:

- https://github.com/postmanlabs/newman/issues/2357
- https://github.com/postmanlabs/newman/issues/941

**Comment by svarshney2311** [comment] 2020-06-30 17:16
Thank you. It worked Perfectly for me the way I wanted. I will explore  more on Report section. Do you have any refrence for this?

Thanks you!

**Comment by DannyDainton** [comment] 2020-06-30 17:19
Glad it worked for you. 🏆 

> Do you have any refrence for this?

Not sure what you mean by this? 😄 

I'm going to close this out but feel free to reply in the thread 😄

**Closed by DannyDainton** 2020-06-30 17:19 UTC
Labels: environment-issue, newman-related
